export const BLOGS = [
	{
		_id: "1",
		text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
		img: "/blogs/blog1.png",
		user: {
			username: "johndoe",
			profilePic: "/avatars/boy1.png",
			fullname: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profilePic: "/avatars/girl1.png",
					fullname: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "johndoe",
			profilePic: "/avatars/boy2.png",
			fullname: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profilePic: "/avatars/girl2.png",
					fullname: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "/blogs/blog2.png",
		user: {
			username: "johndoe",
			profilePic: "/avatars/boy3.png",
			fullname: "John Doe",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "/blogs/blog3.png",
		user: {
			username: "johndoe",
			profilePic: "/avatars/boy3.png",
			fullname: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profilePic: "/avatars/girl3.png",
					fullname: "Jane Doe",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullname: "John Doe",
		username: "johndoe",
		profilePic: "/avatars/boy2.png",
	},
	{
		_id: "2",
		fullname: "Jane Doe",
		username: "janedoe",
		profilePic: "/avatars/girl1.png",
	},
	{
		_id: "3",
		fullname: "Bob Doe",
		username: "bobdoe",
		profilePic: "/avatars/boy3.png",
	},
	{
		_id: "4",
		fullname: "Daisy Doe",
		username: "daisydoe",
		profilePic: "/avatars/girl2.png",
	},
];